modLoader="javafml"
loaderVersion="[32,)"
#updateJSONURL=""
issueTrackerURL="${mod_source_url}/issues"
displayURL="${mod_source_url}"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="${mod_author}"
license="${mod_license}"

[[mods]]
modId="${mod_slug}"
version="${mod_version}"
displayName="${mod_name}"
description="${mod_description}"

[[dependencies.${mod_slug}]]
modId="forge"
mandatory=true
versionRange="[43.1.55,44.0.0)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_slug}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_slug}]]
modId="ae2"
mandatory=false
versionRange="[${ae2_version},13.0.0)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_slug}]]
modId="emi"
mandatory=false
versionRange="[${emi_version},)"
ordering="AFTER"
side="CLIENT"
